config/routes.rb
Rideshare::Application.routes.draw do
  root :to => 'trips#index'
  resources :trips
  
  match  'locations/autocomplete_proxy' => 'locations#autocomplete_proxy'
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', :as => :signout
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :trips_starting_at,  :foreign_key => "start_location_id",  :class_name => "Trip"
  has_many :trips_finishing_at, :foreign_key => "finish_location_id", :class_name => "Trip"
  
  validates :latitude, :presence => true
  validates :longitude, :presence => true
  
  def self.distance(a, b)
    Math.sqrt(
        ((a.latitude - b.latitude) ** 2) +
        ((a.longitude - b.longitude) ** 2))
  end
  
  def self.get_location(string)
    if !(location = Location.find_by_name(string)) 
      latlng = Trip.latlngFinder(string)
      location = Location.create(:name => string, :latitude => latlng["lat"], :longitude => latlng["lng"]) if latlng != nil
    end
    
    location
  end
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to  :user
  belongs_to  :start_location,  :foreign_key => "start_location_id",  :class_name => "Location"
  belongs_to  :finish_location, :foreign_key => "finish_location_id", :class_name => "Location"

  validates_inclusion_of :has_driver, :in => [true, false]
  validates :cost, :presence => true, :numericality => true 
  validates :start_location, :presence => true
  validates :finish_location, :presence => true
  
  def self.filter_by_date_and_start_and_finish_location(
    first_date,
    last_date,
    start_location,
    finish_location,
    max_start_distance_offset=0.5,
    max_finish_distance_offset=0.5)
    
    trips = Trip.where(:departure => first_date..last_date)
    trips.delete_if {|trip| 
        Location.distance(start_location, trip.start_location) > max_start_distance_offset}
    trips.delete_if {|trip|
        Location.distance(finish_location, trip.finish_location) > max_finish_distance_offset}
    
    # TODO(gaye): Maybe sort by proximity on the filtered list
  end
  
  # Takes a string location and returns a hash with the latitude and longitude in the form {"lat" => lat, "lng" => lng}
	def self.latlngFinder(location)
		# Tries to standardize input to a format that google maps likes
  	location = location.strip().gsub(/\s+/,"+")
		# Makes a call to the google maps api
		response= Net::HTTP.get(URI("http://maps.googleapis.com/maps/api/geocode/json?address=#{location}&sensor=false"))
		# Parses the JSON results
		result = JSON.parse(response)
		begin
		  lat = result ["results"][0]["geometry"]["location"]["lat"]
		  lng = result ["results"][0]["geometry"]["location"]["lng"]
		  
		  latlng = {"lat" => lat, "lng" => lng}
		  return latlng
		rescue NoMethodError
		  return nil
	  end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :trips

  def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["info"]["name"]
    user.url = auth["info"]["urls"]["Facebook"]
    user.image = auth["info"]["image"]
    end
  end
  
  def self.update_with_omniauth(auth)
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"])
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["info"]["name"]
    user.url = auth["info"]["urls"]["Facebook"]
    user.image = auth["info"]["image"]
    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end
end

app/controllers/locations_controller.rb
require "net/https"
require "uri"

class LocationsController < ApplicationController
  GOOGLE_MAPS = 'maps.googleapis.com'
  
  def autocomplete_proxy
    uri = URI.parse(CGI.unescape(params['url']))

    if uri.host == GOOGLE_MAPS
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    
      request = Net::HTTP::Get.new(uri.request_uri)
      body = http.request(request).body
    
      respond_to do |format|
        format.html
        format.json { render :json => body }
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    	auth = request.env["omniauth.auth"] 

      if User.find_by_provider_and_uid(auth["provider"], auth["uid"])
        user = User.update_with_omniauth(auth)
    	else 
    	  user = User.create_with_omniauth(auth)
    	end

   		session[:user_id] = user.id
    	redirect_to Rails.cache.read("return_url"), :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    if params[:search]
      start_location = Location.get_location(params[:start_location])
      finish_location = Location.get_location(params[:finish_location])
      
      @trips = Trip.filter_by_date_and_start_and_finish_location(
          Date.new(
              params[:search]['first_date(1i)'].to_i,
              params[:search]['first_date(2i)'].to_i,
              params[:search]['first_date(3i)'].to_i),
          Date.new(
             params[:search]['last_date(1i)'].to_i,
             params[:search]['last_date(2i)'].to_i,
             params[:search]['last_date(3i)'].to_i),
          start_location,
          finish_location,
          params[:search][:max_start_distance_offset] || 0.5,
          params[:search][:max_finish_distance_offset] || 0.5)
    else
      @trips = Trip.where("departure > ?", Time.now)
    end
    
    respond_to do |format|
      format.html
      format.json { render :json => @trips }
    end
  end
  
  def show
    @trip = Trip.find(params[:id], :include => :user)
  end
  
  def new
    @trip = Trip.new
  end
  
  def edit
    @trip = Trip.find(params[:id])
  end
  
  def create
    start_location = Location.get_location(params[:trip].delete(:start_location))
    end_location = Location.get_location(params[:trip].delete(:finish_location))
    valid = false;
    
    if (start_location && end_location)
      params[:trip][:start_location_id] = start_location.id
      params[:trip][:finish_location_id] = end_location.id
      params[:trip][:user] = current_user
      valid = true
    end
    @trip = Trip.new(params[:trip])
    @trip.errors.add(:start_location, "Invalid location entered") unless (valid)
    respond_to do |format|
      if @trip.save && valid
        format.html { redirect_to @trip, :notice => "Created a new trip" }
      else
        format.html { render :action => 'new' }
      end
    end 
  end
  
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trips_url, :notice => "You totally annihilated that trip!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
require 'net/http'
require 'json'

module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Middlebury RideShare</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?sensor=false" %>
  <%= javascript_include_tag "//connect.facebook.net/en_US/all.js#xfbml=1&appId=224061857645056" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="facebook">
	<div class="fb-like" data-href="http://www.facebook.com/pages/Middlebury-Ride-Share/342362625817051" data-send="false" data-width="40" data-show-faces="false"></div>
	<div class="fb-login">
	<% if current_user %>
  	  Welcome, <%= current_user.name %>! <br>
  	  <%= link_to image_tag( 'facebook-logout-button.png'), signout_path %>
	<% else %>
	  <% Rails.cache.write("return_url",request.url) %>
   	  <%= link_to image_tag( 'facebook-login-button.png'), "/auth/facebook" %>
	<% end %>
	</div>
</div>

<div class="bigbox">
  <div id="logo">
    <%= link_to image_tag("logo2.png"), root_path %>
  </div>
  
  <table align="center">
    <tr>
      <td>
        <%= link_to 'Search', root_path, :class => 'button' %>
      </td>
      <td>
        <%= link_to 'Offer/Request a Ride', new_trip_path, :class => 'button' %>
      </td>
    </tr>
  </table>
  
  <%= yield %>
</div>

</body>
</html>


app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :start_location %>
    <%= f.text_field :start_location, :class => "location_autocomplete" %>
  </div>
  <br />
  
  <div class="field">
    <%= f.label :finish_location %>
    <%= f.text_field :finish_location, :class => "location_autocomplete" %>
  </div>
  <br />
  
  <div class="field">
    <%= f.label :departure %>
    <%= f.datetime_select :departure, :ampm => true, :discard_minute => true, :start_year => Date.today.year, :end_year => Date.today.year+1 %>
  </div>
  <br />
  
  <div class="field">
    <%= f.label :cost %>
    <%= f.text_field :cost %>
  </div>
  <br />
  
  Are you a:
  <div class="field">
    Driver <%= f.radio_button :has_driver, true %>
    Passenger <%= f.radio_button :has_driver, false %>
  </div>
  <br />
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/trips/_trip.html.erb
<div class="trip <%= trip.has_driver ? 'left' : 'right' %>">
  
  <table class='tripdisplay'>
    <tr>
      
      <td class='left'>
        <% if trip.has_driver %>
		      <% if current_user %>
            <%= image_tag trip.user.image, :width => 75, :height => 75 %>
            <br />
            <%= link_to trip.user.name, trip.user.url %>
	        <% else %>
	          <%= link_to image_tag( 'unknownUser.png'), "/auth/facebook" %>
            <br />
            <%= link_to 'Login', "/auth/facebook" %> to see who posted this ride!
		      <% end %>
        <% else %>
          <div class='price'><%= trip.cost > 0 ? number_to_currency(trip.cost, :precision => 0) : 'Free' %></div>
        <% end %>
      </td>
  
      <td class='middle'>
        <%= link_to_unless_current "#{trip.has_driver ? 'Offering' : 'Requesting'} a ride...", trip %>
        <br />
        <%= trip.start_location.name %> &#8594; <%= trip.finish_location.name %>
        <br />
        <%= trip.departure.strftime("%A, %B %d, %Y at %I%p") %>
      </td>
  
      <td class='right'>
        <% if trip.has_driver %>
          <!-- TODO(danielhtrauner: Fix the fact that we have the same code here and above) -->
          <!-- TODO(danielhtrauner: Move this to helpers; computations shouldn't happen in the views for view code) -->
          <div class='price'><%= trip.cost > 0 ? number_to_currency(trip.cost, :precision => 0) : 'Free' %></div>
        <% else %>
          <% if current_user %>
            <%= image_tag trip.user.image, :width => 75, :height => 75 %>
            <br />
            <%= link_to trip.user.name, trip.user.url %>
		      <% else %>
			      <%= link_to image_tag( 'unknownUser.png'), "/auth/facebook" %>
            <br />
            <%= link_to 'Login', "/auth/facebook" %> to see who posted this ride!
		      <% end %>
        <% end %>
      </td>
      
    </tr>
  </table>

</div>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<div id="search">
  <%= form_tag('/trips', :method => 'get', :id => 'search_form') do %>
    <%= text_field_tag :start_location, 'From...', {:class => 'location_autocomplete', :id => 'start_location'} %><br /><br />
    <%= text_field_tag :finish_location, 'To...', {:class => 'location_autocomplete', :id => 'end_location'} %><br /><br />
    
    Departure Range
    <br />
    <br />
    Start: <%= date_select :search, :first_date, :start_year => Date.today.year, :end_year => Date.today.year+1  %><br />
    <br />
    End: <%= date_select :search, :last_date, :start_year => Date.today.year, :end_year => Date.today.year+1  %><br />
    <br />
  <% end %>
  
  <div class="button" id="search_button">Search</div>
</div>

<div id="showTrips">
  <%= render :partial => @trips.reverse %>
</div>

app/views/trips/new.html.erb
<div id="post_trip">
  <h1>Offer/Request a Ride</h1>
  <% if current_user %>
    <%= render 'form' %>
  <% else %>
    Please login with Facebook to offer/request a ride
  <% end %>
</div>

app/views/trips/show.html.erb
<div id="trip">
  <table>
    <tr>
      <td>  
        <div id="title">
          <%= @trip.has_driver ? "I have an open seat in my car!" : "I'm looking for a ride!"%>
        </div>

        <div id=<%= current_user && @trip.user.id == current_user.id ? 'delete_link' : 'user_link' %>>
          <% if current_user && @trip.user.id == current_user.id %>
            <%= link_to 'Delete this trip', {:controller=>:trips, :action=>:destroy, :id=>@trip.id}, :method=>:delete, :confirm=>'Are you sure you want to permanently delete this trip?' %>
          <% else %>
            <% if current_user %>
              <%= link_to @trip.user.name, @trip.user.url %>   
         	  <% else %>
              <%= link_to 'Login', "/auth/facebook" %> to see who posted this ride!
        	  <% end %>  
          <% end %>
        </div>
      
        <br/>
      
        <div id="from" class="white_circle"> 
          <%= @trip.start_location.name %>
        </div>
    
        <%= image_tag "right-arrow.png", :width => "130px", :id => "arrow" %>
        
        <div id="to" class="white_circle">
          <%= @trip.finish_location.name %>
        </div>
    
        <div class="clear"></div>
        <div id="map"></div>
      </td>
    </tr>
    
    <tr>
      <td>
        <div id='comments'>
          <div id="fb-root"></div>
          <div class="fb-comments" data-href=<%= request.url %> data-num-posts="7" data-width="600"></div>
        </div>
      </td>
    </tr>
    
  </table>
</div>